version: '3'
services:
  unifi:
    build: ./src
    image: twanislas/unifi
    restart: unless-stopped
    hostname: unifi
    expose:
      - 1900/udp
      - 3478/udp
      - 5656-5699/udp
      - 6789/tcp
      - 8080/tcp
      - 8443/tcp
      - 8843/tcp
      - 8880/tcp
      - 10001/udp
    ports:
      - 1900:1900/udp
      - 3478:3478/udp
      - 5656-5699:5656-5699/udp
      - 6789:6789/tcp
      - 8080:8080/tcp
      - 8443:8443/tcp
      - 8843:8843/tcp
      - 8880:8880/tcp
      - 10001:10001/udp
    volumes:
      - ./config/unifi:/var/lib/unifi
      - ./config/certbot:/etc/letsencrypt