version: '2'
services:
  unifi-controller:
    build: ./src
    image: twanislas/unifi
    restart: unless-stopped
    environment:
      - MEM_LIMIT=1024M
    ports:
      # L2 / Local
      - 1900:1900/udp # Port used for "Make controller discoverable on L2 network" in controller settings.
      - 10001:10001/udp # Port used for device discovery
      - 5656-5699:5656-5699/udp # Ports used by AP-EDU broadcasting.
      # L3 / Remote
      - 3478:3478/udp # Port used for STUN.
      - 5514:5514/tcp # Port used for remote syslog capture.
      - 6789:6789/tcp # Port used for UniFi mobile speed test.
      - 8080:8080/tcp # Port used for device and controller communication.
      - 8443:8443/tcp # Port used for controller GUI/API as seen in a web browser
      - 8843:8843/tcp # Port used for HTTPS portal redirection.
      - 8880:8880/tcp # Port used for HTTP portal redirection.
    volumes:
      - ./config/unifi:/var/lib/unifi
      - ./config/certbot:/etc/letsencrypt