#!/usr/bin/with-contenv bash

# Make sure symlink to /config are good
[[ -L /usr/lib/unifi/data && ! /usr/lib/unifi/data -ef /config ]] && unlink /usr/lib/unifi/data
[[ ! -L /usr/lib/unifi/data ]] && ln -s /config /usr/lib/unifi/data
chown -R unifi:unifi /config /usr/lib/unifi

echo "Starting Unifi Controller."
cd /usr/lib/unifi
exec s6-setuidgid unifi java -Dunifi.datadir=/config -Xmx1024M -jar /usr/lib/unifi/lib/ace.jar start
